### PR TITLE
Use changes from jupyterlab_server

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
@Zsailer, I think what I'm seeing here is that we can't launch an `ExtensionApp` that isn't registered:

```python
[I 2020-08-05 06:10:50.607 ServerApp] __main__ | extension was successfully linked.
[W 2020-08-05 06:10:50.704 ServerApp] module '__main__' has no attribute 'load_jupyter_server_extension'
[I 2020-08-05 06:10:50.704 ServerApp] Serving notebooks from local directory: /Users/stslve/workspace/jupyter/jupyterlab-module-federation
[I 2020-08-05 06:10:50.705 ServerApp] Jupyter Server 1.0.0rc4 is running at:
[I 2020-08-05 06:10:50.705 ServerApp] http://localhost:8888/lab?token=4c84e61e27470f3f47d395667d2063469fece15967c82403
[I 2020-08-05 06:10:50.705 ServerApp]  or http://127.0.0.1:8888/lab?token=4c84e61e27470f3f47d395667d2063469fece15967c82403
[I 2020-08-05 06:10:50.705 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2020-08-05 06:10:50.712 ServerApp]

    To access the server, open this file in a browser:
        file:///Users/stslve/Library/Jupyter/runtime/jpserver-69398-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=4c84e61e27470f3f47d395667d2063469fece15967c82403
     or http://127.0.0.1:8888/lab?token=4c84e61e27470f3f47d395667d2063469fece15967c82403
[E 2020-08-05 06:10:52.634 ServerApp] Could not open static file ''
[W 2020-08-05 06:10:52.636 ServerApp] 404 GET /lab?token=4c84e61e27470f3f47d395667d2063469fece15967c82403 (::1) 18.30ms referer=None
[W 2020-08-05 06:10:52.719 ServerApp] 404 GET /static/favicon.ico (::1) 2.16ms referer=None
```

**Comment by Zsailer** [comment]
Looking at this now...

**Comment by Zsailer** [comment]
@blink1073, can you add me as a maintainer on this repo? I'll push changes to this branch as needed

**Comment by blink1073** [comment]
The next thing I was going to look at is whether the examples in the JupyterLab repo [launch](https://github.com/jupyterlab/jupyterlab/blob/499ea4669fb35deeab027ecc727f4900f0f550ae/examples/app/main.py#L27)

**Comment by blink1073** [comment]
[this](https://github.com/jupyterlab/jupyterlab/blob/499ea4669fb35deeab027ecc727f4900f0f550ae/examples/app/main.py#L19) is probably what we're missing.  It would be nice if that were optional when using `launch_instance`.

**Comment by blink1073** [comment]
@Zsailer you should already have access as a member of the committers group afaik

**Comment by Zsailer** [comment]
> this is probably what we're missing. It would be nice if that were optional when using launch_instance.

I see. It *does* create one of these metadata packets for you, if you're module doesn't define a `jupyter_server_extension_points` (see [here](https://github.com/jupyter/jupyter_server/blob/264e0bb6c057b00580e7a09580cffbe989ac6ff7/jupyter_server/extension/utils.py#L78-L81)). This dynamically created metadata, however, uses the module's name as the extension name, which doesn't work when launch_instance is called via `__main__`.

**Comment by Zsailer** [comment]
> @Zsailer you should already have access as a member of the committers group afaik

Weird—it's showing me that I don't have write access. For example, I can't merge this PR. I see this:

Screen Shot 2020-08-05 at 8 30 20 AM

**Comment by blink1073** [comment]
Ha, the group was read-only on the repo, I bumped up the rights.

**Comment by blink1073** [comment]
Notebook meeting is right now ;)

**Comment by echarles** [comment]
ping me if you need help. I have spent time in the jlab code on the example (and other) launcher parts.

**Comment by echarles** [comment]
If extension was not found by name, I have fallen back using `__name__` as name (python would resolve it correctly depending on how you launch). Not sure if it helps here, but can be useful at some point.

**Comment by Zsailer** [comment]
Following @echarles advice, adding the following chunk the file makes the extension discoverable:

```python
def _jupyter_server_extension_points():
    return [{
        "module": __name__,
        "app": ExampleApp
    }]
```

You're right. This should probably be auto-generated when the extension is launched from `__main__`.

**Pull request merged**
